name: CI/CD Pipeline

on: [push]

jobs:
  SAST_SCAN:
    name: Static Application Security Testing (SAST) with Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  
  Image_Scan:
    name: Build Image and Run Image Scan 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v2
      with:
        docker-version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    # - name: Docker Scout Scan
    #   run: |
    #     # Install Docker Scout CLI
    #     curl -fsSl https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
    #     sh install-scout.sh
    #     # Authenticate Docker Scout
    #     echo "${{ secrets.DOCKER_PWD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #     # Run Docker Scout commands
    #     docker scout quickstart
    #     docker scout cves

    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif

    - name: Upload Docker Scout Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-scout-findings
        path: docker-scout-report.json